"""
SahajCode Code Generator
Traverses AST and emits equivalent C99 code.
All declarations are inside main(), all executable statements are inside main().
"""

from typing import List, Optional
from .ast_nodes import (
    ASTNode, Program, VarDecl, Assignment, Print, Input,
    If, While, For, BinaryOp, UnaryOp, Number, String, Identifier, Comment, NodeType,
    FunctionDef, Return, Call, ArrayLiteral, IndexExpr
)
from .symbol_table import SymbolTable, VarType, FunctionInfo


class CodeGenerator:
    def __init__(self, symbol_table: SymbolTable):
        self.symbol_table = symbol_table
        self.c_lines: List[str] = []
        self.indent = 0
        self._tmp_counter = 0
        self.source_lines: List[str] = []
        
    def generate(self, ast: Program, source: Optional[str] = None) -> str:
        """Generate C code from AST."""
        self.source_lines = source.split('\n') if source else []
        self.c_lines = [
            "/* Auto-generated by SahajCode transpiler */",
            "#include <stdio.h>",
            "#include <string.h>",
            "",
        ]
        
        # Emit function definitions above main
        func_defs = [s for s in ast.statements if s.node_type == NodeType.FUNCTION_DEF]
        main_stmts = [s for s in ast.statements if s.node_type != NodeType.FUNCTION_DEF]
        
        for fdef in func_defs:
            self._generate_function(fdef)
            self.c_lines.append('')
        
        # main()
        self.c_lines.append("int main() {")
        self.indent = 1
        
        self._declare_variables()
        self._generate_statement_list(main_stmts)
        
        self.indent = 0
        self.c_lines.append("    return 0;")
        self.c_lines.append("}")
        
        return '\n'.join(self.c_lines)
    
    # ---- Function generation ----
    def _infer_param_types(self, fdef: FunctionDef) -> List[VarType]:
        """Infer each parameter's type by scanning the function body for string usage."""
        types = []
        for p in fdef.params:
            if self._param_used_as_string(p, fdef.body):
                types.append(VarType.STRING)
            else:
                types.append(VarType.INT)
        return types
    
    def _param_used_as_string(self, param: str, nodes) -> bool:
        """Heuristic: is `param` used in a string context anywhere in the body?"""
        for n in nodes:
            if n is None or n.node_type == NodeType.FUNCTION_DEF:
                continue
            if n.node_type == NodeType.BINARY_OP and n.op == '+':
                if self._ident_is(n.left, param) and self._is_string_like(n.right):
                    return True
                if self._ident_is(n.right, param) and self._is_string_like(n.left):
                    return True
                if self._param_used_as_string(param, [n.left, n.right]):
                    return True
            if n.node_type == NodeType.PRINT and self._expr_uses_string_param(param, n.expr):
                return True
            if n.node_type in (NodeType.VAR_DECL, NodeType.ASSIGNMENT):
                if self._expr_uses_string_param(param, getattr(n, 'value', None)):
                    return True
            if n.node_type == NodeType.IF and self._expr_uses_string_param(param, n.condition):
                return True
            if n.node_type == NodeType.WHILE and self._expr_uses_string_param(param, n.condition):
                return True
            for child in ('then_branch', 'else_branch', 'body'):
                child_nodes = getattr(n, child, None)
                if isinstance(child_nodes, list) and self._param_used_as_string(param, child_nodes):
                    return True
        return False
    
    def _expr_uses_string_param(self, param: str, expr) -> bool:
        """True if param appears as an operand of a '+' whose other side is string-like."""
        if expr is None:
            return False
        if expr.node_type == NodeType.BINARY_OP and expr.op == '+':
            if self._ident_is(expr.left, param) and self._is_string_like(expr.right):
                return True
            if self._ident_is(expr.right, param) and self._is_string_like(expr.left):
                return True
            return self._expr_uses_string_param(param, expr.left) or self._expr_uses_string_param(param, expr.right)
        if expr.node_type == NodeType.CALL:
            return any(self._expr_uses_string_param(param, a) for a in expr.args)
        return False

    
    def _ident_is(self, node, name: str) -> bool:
        return node is not None and node.node_type == NodeType.IDENTIFIER and node.name == name
    
    def _generate_function(self, fdef: FunctionDef):
        """Emit a C function definition."""
        ret_type = self._infer_return_type(fdef)
        param_types = self._infer_param_types(fdef)
        # Record inferred return type so call sites can infer it too
        fn = self.symbol_table.lookup_function(fdef.name)
        if fn is not None:
            fn.return_type = ret_type
        # Build C signature
        c_params = []
        for p, pt in zip(fdef.params, param_types):
            if pt == VarType.STRING:
                c_params.append(f'char {p}[]')
            else:
                c_params.append(f'int {p}')
        sig = ', '.join(c_params) if c_params else 'void'
        ret_c = 'char*' if ret_type == VarType.STRING else 'int'
        
        self.c_lines.append(f'{ret_c} {fdef.name}({sig}) {{')
        self.indent = 1
        
        # Declare local variables (rakha inside function) excluding params
        locals_seen = set(fdef.params)
        local_decls = []
        self._collect_function_locals(fdef.body, locals_seen, local_decls)
        for decl in local_decls:
            if decl[1] == VarType.STRING:
                self.c_lines.append(f'{self._indent()}char {decl[0]}[256] = {{0}};')
            else:
                self.c_lines.append(f'{self._indent()}int {decl[0]} = 0;')
        if local_decls:
            self.c_lines.append('')
        
        # For string returns, provide a static buffer
        if ret_type == VarType.STRING:
            self.c_lines.append(f'{self._indent()}static char _ret[256];')
            self.c_lines.append('')
        
        # Emit body
        self._generate_statement_list(fdef.body)
        
        self.indent = 0
        # Ensure a return for non-void fallback (int 0)
        self.c_lines.append('}')
    
    def _collect_function_locals(self, nodes, seen: set, out: list):
        for n in nodes:
            if n is None:
                continue
            if n.node_type == NodeType.VAR_DECL:
                if n.name not in seen:
                    seen.add(n.name)
                    vtype = self._infer_node_type_c(n.value)
                    out.append((n.name, vtype))
            elif n.node_type == NodeType.FUNCTION_DEF:
                continue
            elif n.node_type in (NodeType.IF,):
                self._collect_function_locals(n.then_branch, seen, out)
                self._collect_function_locals(n.else_branch, seen, out)
            elif n.node_type in (NodeType.WHILE, NodeType.FOR):
                self._collect_function_locals(n.body, seen, out)
    
    def _infer_return_type(self, fdef: FunctionDef) -> VarType:
        """Infer return type from the first firta expression."""
        for n in fdef.body:
            if n is not None and n.node_type == NodeType.RETURN and n.expr is not None:
                return self._infer_node_type_c(n.expr)
        return VarType.INT
    
    def _infer_node_type_c(self, expr) -> VarType:
        """Lightweight type inference used for local var / return declarations."""
        if expr is None:
            return VarType.INT
        if expr.node_type == NodeType.STRING:
            return VarType.STRING
        if expr.node_type == NodeType.ARRAY_LITERAL:
            return VarType.STRING if expr.elem_type == 'string' else VarType.INT
        if expr.node_type == NodeType.NUMBER:
            return VarType.INT
        if expr.node_type == NodeType.BINARY_OP and expr.op == '+':
            if self._is_string_like(expr.left) or self._is_string_like(expr.right):
                return VarType.STRING
        if expr.node_type == NodeType.IDENTIFIER:
            sym = self.symbol_table.lookup(expr.name)
            if sym:
                return sym.type
            return VarType.INT
        if expr.node_type == NodeType.INDEX:
            sym = self.symbol_table.lookup(expr.array)
            if sym and sym.type == VarType.STRING:
                return VarType.STRING
            return VarType.INT
        if expr.node_type == NodeType.CALL:
            info = self.symbol_table.lookup_function(expr.name)
            if info:
                return info.return_type
            return VarType.INT
        return VarType.INT
    
    def _declare_variables(self):
        """Declare all top-level variables at the beginning of main().

        Variables initialized with an array literal are declared (with their
        initializer) by _generate_var_decl, so they are skipped here to avoid a
        redeclaration.
        """
        for name, symbol in self.symbol_table.symbols.items():
            # Arrays with initializers are declared in _generate_var_decl.
            if symbol.is_array:
                continue
            if symbol.type == VarType.STRING:
                self.c_lines.append(f'{self._indent()}char {name}[256] = {{0}};')
            else:
                self.c_lines.append(f'{self._indent()}int {name} = 0;')
        
        for name, line in self.symbol_table.inputs_pending:
            if name not in self.symbol_table.symbols:
                self.c_lines.append(f'{self._indent()}int {name} = 0;')
        
        if self.symbol_table.symbols or self.symbol_table.inputs_pending:
            self.c_lines.append('')
    
    def _generate_statement_list(self, statements: List[ASTNode]):
        """Generate a list of statements with proper indentation."""
        for stmt in statements:
            self._generate_statement(stmt)
    
    def _line_comment(self, line: int) -> str:
        """Build a source-line comment per PRD F3.1: /* Line X: <source> */."""
        text = ''
        if 1 <= line <= len(self.source_lines):
            text = self.source_lines[line - 1].replace('*/', '* /').strip()
        if text:
            return f'{self._indent()}/* Line {line}: {text} */'
        return f'{self._indent()}/* Line {line} */'
    
    def _generate_statement(self, stmt: ASTNode):
        """Generate code for a single statement."""
        if stmt is None:
            return
        if getattr(stmt, 'line', 0):
            self.c_lines.append(self._line_comment(stmt.line))
        if stmt.node_type == NodeType.VAR_DECL:
            self._generate_var_decl(stmt)
        elif stmt.node_type == NodeType.ASSIGNMENT:
            self._generate_assignment(stmt)
        elif stmt.node_type == NodeType.PRINT:
            self._generate_print(stmt)
        elif stmt.node_type == NodeType.INPUT:
            self._generate_input(stmt)
        elif stmt.node_type == NodeType.IF:
            self._generate_if(stmt)
        elif stmt.node_type == NodeType.WHILE:
            self._generate_while(stmt)
        elif stmt.node_type == NodeType.FOR:
            self._generate_for(stmt)
        elif stmt.node_type == NodeType.RETURN:
            self._generate_return(stmt)
        elif stmt.node_type == NodeType.CALL:
            self.c_lines.append(f'{self._indent()}{self._gen_expr(stmt)};')
        elif stmt.node_type == NodeType.COMMENT:
            self.c_lines.append(f'{self._indent()}/* {stmt.text} */')
        # FUNCTION_DEF handled separately (emitted above main)
    
    def _generate_return(self, stmt: Return):
        if stmt.expr is None:
            self.c_lines.append(f'{self._indent()}return;')
            return
        ret_type = self._infer_node_type_c(stmt.expr)
        if ret_type == VarType.STRING:
            val = self._gen_expr(stmt.expr)
            self.c_lines.append(f'{self._indent()}strcpy(_ret, {val});')
            self.c_lines.append(f'{self._indent()}return _ret;')
        else:
            self.c_lines.append(f'{self._indent()}return {self._gen_expr(stmt.expr)};')
    
    def _generate_var_decl(self, stmt: VarDecl):
        """Generate variable declaration with initialization."""
        if stmt.value is not None:
            if stmt.value.node_type == NodeType.ARRAY_LITERAL:
                self._generate_array_decl(stmt.name, stmt.value)
                return
            if self._is_string_concat(stmt.value):
                self._generate_string_concat(stmt.name, stmt.value)
                return
            self._emit_division_guards(stmt.value)
            expr = self._gen_expr(stmt.value)
            if isinstance(stmt.value, String):
                self.c_lines.append(f'{self._indent()}strcpy({stmt.name}, {expr});')
            else:
                self.c_lines.append(f'{self._indent()}{stmt.name} = {expr};')
    
    def _generate_array_decl(self, name: str, arr: ArrayLiteral):
        parts = [self._gen_expr(e) for e in arr.elements]
        if arr.elem_type == 'string':
            self.c_lines.append(f'{self._indent()}char {name}[{arr.size}][256] = {{')
            for i, p in enumerate(parts):
                comma = ',' if i < len(parts) - 1 else ''
                self.c_lines.append(f'{self._indent()}    {p}{comma}')
            self.c_lines.append(f'{self._indent()}}};')
        else:
            self.c_lines.append(f'{self._indent()}int {name}[{arr.size}] = {{{", ".join(parts)}}};')
    
    def _generate_assignment(self, stmt: Assignment):
        """Generate assignment statement (identifier or array index target)."""
        target = getattr(stmt, 'target', None)
        if target is not None and target.node_type == NodeType.INDEX:
            self._generate_index_assignment(target, stmt.value)
            return
        if self._is_string_concat(stmt.value):
            self._generate_string_concat(stmt.name, stmt.value)
            return
        self._emit_division_guards(stmt.value)
        expr = self._gen_expr(stmt.value)
        if isinstance(stmt.value, String):
            self.c_lines.append(f'{self._indent()}strcpy({stmt.name}, {expr});')
        else:
            self.c_lines.append(f'{self._indent()}{stmt.name} = {expr};')
    
    def _generate_index_assignment(self, target: IndexExpr, value):
        arr = target.array
        idx = self._gen_expr(target.index)
        sym = self.symbol_table.lookup(arr)
        is_string = (sym and sym.type == VarType.STRING) or target.is_string
        if is_string:
            self._emit_division_guards(value)
            self.c_lines.append(f'{self._indent()}strcpy({arr}[{idx}], {self._gen_expr(value)});')
        else:
            self._emit_division_guards(value)
            self.c_lines.append(f'{self._indent()}{arr}[{idx}] = {self._gen_expr(value)};')
    
    def _generate_print(self, stmt: Print):
        """Generate print statement."""
        expr = stmt.expr
        if expr is None:
            return
        self._emit_division_guards(expr)
        if self._is_string_concat(expr):
            buf = f'_sc_print_{self._tmp_counter}'
            self._tmp_counter += 1
            self.c_lines.append(f'{self._indent()}char {buf}[256];')
            self._generate_string_concat(buf, expr)
            self.c_lines.append(f'{self._indent()}printf("%s\\n", {buf});')
            return
        expr_type = self._infer_expr_type(expr)
        expr_str = self._gen_expr(expr)
        if expr_type == VarType.STRING:
            self.c_lines.append(f'{self._indent()}printf("%s\\n", {expr_str});')
        else:
            self.c_lines.append(f'{self._indent()}printf("%d\\n", {expr_str});')
    
    def _generate_input(self, stmt: Input):
        """Generate input statement."""
        var_type = self.symbol_table.lookup(stmt.name)
        if var_type and var_type.type == VarType.STRING:
            self.c_lines.append(f'{self._indent()}fgets({stmt.name}, sizeof({stmt.name}), stdin);')
            self.c_lines.append(f'{self._indent()}{stmt.name}[strcspn({stmt.name}, "\\n")] = 0;')
        else:
            self.c_lines.append(f'{self._indent()}scanf("%d", &{stmt.name});')
    
    def _generate_if(self, stmt: If):
        """Generate if statement."""
        # Runtime division-by-zero guard inside condition (PRD E006)
        self._emit_division_guards(stmt.condition)
        condition = self._gen_expr(stmt.condition)
        self.c_lines.append(f'{self._indent()}if ({condition}) {{')
        self.indent += 1
        self._generate_statement_list(stmt.then_branch)
        self.indent -= 1
        self.c_lines.append(f'{self._indent()}}}')
        
        if stmt.else_branch:
            self.c_lines.append(f'{self._indent()} else {{')
            self.indent += 1
            self._generate_statement_list(stmt.else_branch)
            self.indent -= 1
            self.c_lines.append(f'{self._indent()}}}')
    
    def _generate_while(self, stmt: While):
        """Generate while loop."""
        # Runtime division-by-zero guard inside condition (PRD E006)
        self._emit_division_guards(stmt.condition)
        condition = self._gen_expr(stmt.condition)
        self.c_lines.append(f'{self._indent()}while ({condition}) {{')
        self.indent += 1
        self._generate_statement_list(stmt.body)
        self.indent -= 1
        self.c_lines.append(f'{self._indent()}}}')
    
    def _generate_for(self, stmt: For):
        """Generate for loop: guma var = start dekhi end"""
        start_val = self._gen_expr(stmt.start)
        end_val = self._gen_expr(stmt.end)
        self.c_lines.append(f'{self._indent()}for (int {stmt.var} = {start_val}; {stmt.var} <= {end_val}; {stmt.var}++) {{')
        self.indent += 1
        self._generate_statement_list(stmt.body)
        self.indent -= 1
        self.c_lines.append(f'{self._indent()}}}')
    
    def _gen_expr(self, expr: ASTNode) -> str:
        """Generate expression code."""
        if expr is None:
            return ''
        if expr.node_type == NodeType.NUMBER:
            return str(expr.value)
        elif expr.node_type == NodeType.STRING:
            return f'"{expr.value}"'
        elif expr.node_type == NodeType.IDENTIFIER:
            return expr.name
        elif expr.node_type == NodeType.INDEX:
            return f'{expr.array}[{self._gen_expr(expr.index)}]'
        elif expr.node_type == NodeType.CALL:
            args = ', '.join(self._gen_expr(a) for a in expr.args)
            return f'{expr.name}({args})'
        elif expr.node_type == NodeType.ARRAY_LITERAL:
            inner = ', '.join(self._gen_expr(e) for e in expr.elements)
            return f'{{{inner}}}'
        elif expr.node_type == NodeType.BINARY_OP:
            return self._gen_binary_op(expr)
        elif expr.node_type == NodeType.UNARY_OP:
            return f'({expr.op}{self._gen_expr(expr.operand)})'
        return ''
    
    def _gen_binary_op(self, expr: BinaryOp) -> str:
        """Generate binary operation."""
        left = self._gen_expr(expr.left)
        right = self._gen_expr(expr.right)
        # String comparison must use strcmp, not == / !=
        if expr.op in ('==', '!='):
            left_is_str = self._infer_expr_type(expr.left) == VarType.STRING
            right_is_str = self._infer_expr_type(expr.right) == VarType.STRING
            if left_is_str or right_is_str:
                cmp = '==' if expr.op == '==' else '!='
                return f'(strcmp({left}, {right}) {cmp} 0)'
        # Division by a literal 0 is intercepted by the runtime guard emitted in
        # _emit_division_guards, so the division is unreachable. Substitute a
        # non-zero placeholder divisor to avoid a -Wdiv-by-zero compile warning (PRD F3).
        if expr.op == '/' and expr.right.node_type == NodeType.NUMBER and expr.right.value == 0:
            right = '1'
        return f'({left} {expr.op} {right})'
    
    def _infer_expr_type(self, expr: ASTNode) -> VarType:
        """Infer expression type."""
        if expr.node_type == NodeType.STRING:
            return VarType.STRING
        elif expr.node_type == NodeType.IDENTIFIER:
            sym = self.symbol_table.lookup(expr.name)
            return sym.type if sym else VarType.INT
        elif expr.node_type == NodeType.BINARY_OP and expr.op == '+':
            if self._is_string_like(expr.left) or self._is_string_like(expr.right):
                return VarType.STRING
        elif expr.node_type == NodeType.CALL:
            fn = self.symbol_table.lookup_function(expr.name)
            if fn is not None:
                return fn.return_type
        return VarType.INT
    
    def _is_string_like(self, expr: ASTNode) -> bool:
        """True if expr evaluates to a string (literal, string var, or concat)."""
        if expr.node_type == NodeType.STRING:
            return True
        if expr.node_type == NodeType.IDENTIFIER:
            return self._infer_expr_type(expr) == VarType.STRING
        return self._is_string_concat(expr)
    
    def _is_string_concat(self, expr: ASTNode) -> bool:
        """True if expr is a '+' whose result is a string (per PRD §6.5)."""
        if expr.node_type == NodeType.BINARY_OP and expr.op == '+':
            return (self._is_string_like(expr.left) or
                    self._is_string_like(expr.right))
        return False
    
    def _flatten_concat(self, expr: ASTNode, operands: list):
        """Flatten a left-associative '+' chain into a list of operands."""
        if expr.node_type == NodeType.BINARY_OP and expr.op == '+':
            self._flatten_concat(expr.left, operands)
            self._flatten_concat(expr.right, operands)
        else:
            operands.append(expr)
    
    def _generate_string_concat(self, target: str, expr: ASTNode):
        """Generate strcpy/strcat/sprintf statements building a string in target."""
        operands = []
        self._flatten_concat(expr, operands)
        first = True
        for op in operands:
            op_c = self._gen_expr(op)
            if self._infer_expr_type(op) == VarType.STRING:
                if first:
                    self.c_lines.append(f'{self._indent()}strcpy({target}, {op_c});')
                else:
                    self.c_lines.append(f'{self._indent()}strcat({target}, {op_c});')
            else:
                buf = f'_sc_buf_{self._tmp_counter}'
                self._tmp_counter += 1
                self.c_lines.append(f'{self._indent()}char {buf}[32];')
                self.c_lines.append(f'{self._indent()}sprintf({buf}, "%d", {op_c});')
                if first:
                    self.c_lines.append(f'{self._indent()}strcpy({target}, {buf});')
                else:
                    self.c_lines.append(f'{self._indent()}strcat({target}, {buf});')
            first = False
    
    def _emit_division_guards(self, expr: ASTNode):
        """Emit a runtime division-by-zero guard for every '/' in expr (PRD E006).

        Catches both literal (/ 0) and variable (a / b where b == 0) divisors.
        """
        if expr is None:
            return
        if expr.node_type == NodeType.BINARY_OP:
            if expr.op == '/':
                divisor = self._gen_expr(expr.right)
                self.c_lines.append(f'{self._indent()}if ({divisor} == 0) {{')
                self.indent += 1
                self.c_lines.append(f'{self._indent()}fprintf(stderr, "Runtime: Cannot divide by zero\\n");')
                self.c_lines.append(f'{self._indent()}return 1;')
                self.indent -= 1
                self.c_lines.append(f'{self._indent()}}}')
            self._emit_division_guards(expr.left)
            self._emit_division_guards(expr.right)
    
    def _indent(self) -> str:
        return '    ' * self.indent


def generate_c(ast: Program, symbol_table: SymbolTable, source: Optional[str] = None) -> str:
    """Generate C code from AST."""
    gen = CodeGenerator(symbol_table)
    return gen.generate(ast, source)