"""
SahajCode Code Generator
Traverses AST and emits equivalent C99 code.
All declarations are inside main(), all executable statements are inside main().
"""

from typing import List, Optional
from .ast_nodes import (
    ASTNode, Program, VarDecl, Assignment, Print, Input,
    If, While, For, BinaryOp, UnaryOp, Number, String, Identifier, Comment, NodeType
)
from .symbol_table import SymbolTable, VarType


class CodeGenerator:
    def __init__(self, symbol_table: SymbolTable):
        self.symbol_table = symbol_table
        self.c_lines: List[str] = []
        self.indent = 0
        self._tmp_counter = 0
        self.source_lines: List[str] = []
        
    def generate(self, ast: Program, source: Optional[str] = None) -> str:
        """Generate C code from AST."""
        self.source_lines = source.split('\n') if source else []
        self.c_lines = [
            "/* Auto-generated by SahajCode transpiler */",
            "#include <stdio.h>",
            "#include <string.h>",
            "",
            "int main() {"
        ]
        self.indent = 1
        
        # Declare all variables at the start of main
        self._declare_variables()
        
        # Generate statements
        self._generate_statement_list(ast.statements)
        
        self.indent = 0
        self.c_lines.append("    return 0;")
        self.c_lines.append("}")
        
        return '\n'.join(self.c_lines)
    
    def _declare_variables(self):
        """Declare all variables at the beginning of main()."""
        # Declare variables from VAR_DECL statements
        for name, symbol in self.symbol_table.symbols.items():
            if symbol.type == VarType.STRING:
                self.c_lines.append(f'{self._indent()}char {name}[256] = {{0}};')
            else:
                self.c_lines.append(f'{self._indent()}int {name} = 0;')
        
        # Declare variables from INPUT statements (suna) that weren't explicitly declared
        for name, line in self.symbol_table.inputs_pending:
            if name not in self.symbol_table.symbols:
                # Input variables default to int type
                self.c_lines.append(f'{self._indent()}int {name} = 0;')
        
        # Add blank line after declarations if we have any
        if self.symbol_table.symbols or self.symbol_table.inputs_pending:
            self.c_lines.append('')
    
    def _generate_statement_list(self, statements: List[ASTNode]):
        """Generate a list of statements with proper indentation."""
        for stmt in statements:
            self._generate_statement(stmt)
    
    def _line_comment(self, line: int) -> str:
        """Build a source-line comment per PRD F3.1: /* Line X: <source> */."""
        text = ''
        if 1 <= line <= len(self.source_lines):
            text = self.source_lines[line - 1].replace('*/', '* /').strip()
        if text:
            return f'{self._indent()}/* Line {line}: {text} */'
        return f'{self._indent()}/* Line {line} */'
    
    def _generate_statement(self, stmt: ASTNode):
        """Generate code for a single statement."""
        if getattr(stmt, 'line', 0):
            self.c_lines.append(self._line_comment(stmt.line))
        if stmt.node_type == NodeType.VAR_DECL:
            self._generate_var_decl(stmt)
        elif stmt.node_type == NodeType.ASSIGNMENT:
            self._generate_assignment(stmt)
        elif stmt.node_type == NodeType.PRINT:
            self._generate_print(stmt)
        elif stmt.node_type == NodeType.INPUT:
            self._generate_input(stmt)
        elif stmt.node_type == NodeType.IF:
            self._generate_if(stmt)
        elif stmt.node_type == NodeType.WHILE:
            self._generate_while(stmt)
        elif stmt.node_type == NodeType.FOR:
            self._generate_for(stmt)
        elif stmt.node_type == NodeType.COMMENT:
            # Comments are preserved as C comments
            self.c_lines.append(f'{self._indent()}/* {stmt.text} */')
    
    def _generate_var_decl(self, stmt: VarDecl):
        """Generate variable declaration with initialization."""
        if stmt.value is not None:
            # String concatenation requires strcpy/strcat, not '='
            if self._is_string_concat(stmt.value):
                self._generate_string_concat(stmt.name, stmt.value)
                return
            
            # Runtime division-by-zero guard (PRD E006)
            self._emit_division_guards(stmt.value)
            
            expr = self._gen_expr(stmt.value)
            # For strings, we need to use strcpy
            if isinstance(stmt.value, String):
                self.c_lines.append(f'{self._indent()}strcpy({stmt.name}, {expr});')
            else:
                self.c_lines.append(f'{self._indent()}{stmt.name} = {expr};')
        # If no initialization, variable already declared with default value
    
    def _generate_assignment(self, stmt: Assignment):
        """Generate assignment statement."""
        # String concatenation requires strcpy/strcat, not '='
        if self._is_string_concat(stmt.value):
            self._generate_string_concat(stmt.name, stmt.value)
            return
        
        # Runtime division-by-zero guard (PRD E006)
        self._emit_division_guards(stmt.value)
        
        expr = self._gen_expr(stmt.value)
        # For strings, use strcpy
        if isinstance(stmt.value, String):
            self.c_lines.append(f'{self._indent()}strcpy({stmt.name}, {expr});')
        else:
            self.c_lines.append(f'{self._indent()}{stmt.name} = {expr};')
    
    def _generate_print(self, stmt: Print):
        """Generate print statement."""
        expr = stmt.expr
        if expr is None:
            return
        
        # Runtime division-by-zero guard (PRD E006)
        self._emit_division_guards(expr)
        
        # String concatenation: build into a temp buffer, then print
        if self._is_string_concat(expr):
            buf = f'_sc_print_{self._tmp_counter}'
            self._tmp_counter += 1
            self.c_lines.append(f'{self._indent()}char {buf}[256];')
            self._generate_string_concat(buf, expr)
            self.c_lines.append(f'{self._indent()}printf("%s\\n", {buf});')
            return
        
        expr_type = self._infer_expr_type(expr)
        expr_str = self._gen_expr(expr)
        
        if expr_type == VarType.STRING:
            self.c_lines.append(f'{self._indent()}printf("%s\\n", {expr_str});')
        else:
            self.c_lines.append(f'{self._indent()}printf("%d\\n", {expr_str});')
    
    def _generate_input(self, stmt: Input):
        """Generate input statement."""
        # Check if variable is string or int
        var_type = self.symbol_table.lookup(stmt.name)
        if var_type and var_type.type == VarType.STRING:
            self.c_lines.append(f'{self._indent()}fgets({stmt.name}, sizeof({stmt.name}), stdin);')
            self.c_lines.append(f'{self._indent()}{stmt.name}[strcspn({stmt.name}, "\\n")] = 0;')  # Remove newline
        else:
            self.c_lines.append(f'{self._indent()}scanf("%d", &{stmt.name});')
    
    def _generate_if(self, stmt: If):
        """Generate if statement."""
        # Runtime division-by-zero guard inside condition (PRD E006)
        self._emit_division_guards(stmt.condition)
        condition = self._gen_expr(stmt.condition)
        self.c_lines.append(f'{self._indent()}if ({condition}) {{')
        self.indent += 1
        self._generate_statement_list(stmt.then_branch)
        self.indent -= 1
        self.c_lines.append(f'{self._indent()}}}')
        
        if stmt.else_branch:
            self.c_lines.append(f'{self._indent()} else {{')
            self.indent += 1
            self._generate_statement_list(stmt.else_branch)
            self.indent -= 1
            self.c_lines.append(f'{self._indent()}}}')
    
    def _generate_while(self, stmt: While):
        """Generate while loop."""
        # Runtime division-by-zero guard inside condition (PRD E006)
        self._emit_division_guards(stmt.condition)
        condition = self._gen_expr(stmt.condition)
        self.c_lines.append(f'{self._indent()}while ({condition}) {{')
        self.indent += 1
        self._generate_statement_list(stmt.body)
        self.indent -= 1
        self.c_lines.append(f'{self._indent()}}}')
    
    def _generate_for(self, stmt: For):
        """Generate for loop: guma var = start dekhi end"""
        start_val = self._gen_expr(stmt.start)
        end_val = self._gen_expr(stmt.end)
        self.c_lines.append(f'{self._indent()}for (int {stmt.var} = {start_val}; {stmt.var} <= {end_val}; {stmt.var}++) {{')
        self.indent += 1
        self._generate_statement_list(stmt.body)
        self.indent -= 1
        self.c_lines.append(f'{self._indent()}}}')
    
    def _gen_expr(self, expr: ASTNode) -> str:
        """Generate expression code."""
        if expr.node_type == NodeType.NUMBER:
            return str(expr.value)
        elif expr.node_type == NodeType.STRING:
            return f'"{expr.value}"'
        elif expr.node_type == NodeType.IDENTIFIER:
            return expr.name
        elif expr.node_type == NodeType.BINARY_OP:
            return self._gen_binary_op(expr)
        elif expr.node_type == NodeType.UNARY_OP:
            return f'({expr.op}{self._gen_expr(expr.operand)})'
        return ''
    
    def _gen_binary_op(self, expr: BinaryOp) -> str:
        """Generate binary operation."""
        left = self._gen_expr(expr.left)
        right = self._gen_expr(expr.right)
        # String comparison must use strcmp, not == / !=
        if expr.op in ('==', '!='):
            left_is_str = self._infer_expr_type(expr.left) == VarType.STRING
            right_is_str = self._infer_expr_type(expr.right) == VarType.STRING
            if left_is_str or right_is_str:
                cmp = '==' if expr.op == '==' else '!='
                return f'(strcmp({left}, {right}) {cmp} 0)'
        # Division by a literal 0 is intercepted by the runtime guard emitted in
        # _emit_division_guards, so the division is unreachable. Substitute a
        # non-zero placeholder divisor to avoid a -Wdiv-by-zero compile warning (PRD F3).
        if expr.op == '/' and expr.right.node_type == NodeType.NUMBER and expr.right.value == 0:
            right = '1'
        return f'({left} {expr.op} {right})'
    
    def _infer_expr_type(self, expr: ASTNode) -> VarType:
        """Infer expression type."""
        if expr.node_type == NodeType.STRING:
            return VarType.STRING
        elif expr.node_type == NodeType.IDENTIFIER:
            sym = self.symbol_table.lookup(expr.name)
            return sym.type if sym else VarType.INT
        elif expr.node_type == NodeType.BINARY_OP and expr.op == '+':
            if self._is_string_like(expr.left) or self._is_string_like(expr.right):
                return VarType.STRING
        return VarType.INT
    
    def _is_string_like(self, expr: ASTNode) -> bool:
        """True if expr evaluates to a string (literal, string var, or concat)."""
        if expr.node_type == NodeType.STRING:
            return True
        if expr.node_type == NodeType.IDENTIFIER:
            return self._infer_expr_type(expr) == VarType.STRING
        return self._is_string_concat(expr)
    
    def _is_string_concat(self, expr: ASTNode) -> bool:
        """True if expr is a '+' whose result is a string (per PRD §6.5)."""
        if expr.node_type == NodeType.BINARY_OP and expr.op == '+':
            return (self._is_string_like(expr.left) or
                    self._is_string_like(expr.right))
        return False
    
    def _flatten_concat(self, expr: ASTNode, operands: list):
        """Flatten a left-associative '+' chain into a list of operands."""
        if expr.node_type == NodeType.BINARY_OP and expr.op == '+':
            self._flatten_concat(expr.left, operands)
            self._flatten_concat(expr.right, operands)
        else:
            operands.append(expr)
    
    def _generate_string_concat(self, target: str, expr: ASTNode):
        """Generate strcpy/strcat/sprintf statements building a string in target."""
        operands = []
        self._flatten_concat(expr, operands)
        first = True
        for op in operands:
            op_c = self._gen_expr(op)
            if self._infer_expr_type(op) == VarType.STRING:
                if first:
                    self.c_lines.append(f'{self._indent()}strcpy({target}, {op_c});')
                else:
                    self.c_lines.append(f'{self._indent()}strcat({target}, {op_c});')
            else:
                buf = f'_sc_buf_{self._tmp_counter}'
                self._tmp_counter += 1
                self.c_lines.append(f'{self._indent()}char {buf}[32];')
                self.c_lines.append(f'{self._indent()}sprintf({buf}, "%d", {op_c});')
                if first:
                    self.c_lines.append(f'{self._indent()}strcpy({target}, {buf});')
                else:
                    self.c_lines.append(f'{self._indent()}strcat({target}, {buf});')
            first = False
    
    def _emit_division_guards(self, expr: ASTNode):
        """Emit a runtime division-by-zero guard for every '/' in expr (PRD E006).

        Catches both literal (/ 0) and variable (a / b where b == 0) divisors.
        """
        if expr is None:
            return
        if expr.node_type == NodeType.BINARY_OP:
            if expr.op == '/':
                divisor = self._gen_expr(expr.right)
                self.c_lines.append(f'{self._indent()}if ({divisor} == 0) {{')
                self.indent += 1
                self.c_lines.append(f'{self._indent()}fprintf(stderr, "Runtime: Cannot divide by zero\\n");')
                self.c_lines.append(f'{self._indent()}return 1;')
                self.indent -= 1
                self.c_lines.append(f'{self._indent()}}}')
            self._emit_division_guards(expr.left)
            self._emit_division_guards(expr.right)
    
    def _indent(self) -> str:
        return '    ' * self.indent


def generate_c(ast: Program, symbol_table: SymbolTable, source: Optional[str] = None) -> str:
    """Generate C code from AST."""
    gen = CodeGenerator(symbol_table)
    return gen.generate(ast, source)